# Generated by Django 4.1.1 on 2022-09-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_counselor_description_counselor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselor',
            name='user_name',
            field=models.CharField(default='hi', max_length=50, verbose_name='user_name'),
            preserve_default=False,
        ),
    ]
