# Generated by Django 4.1.1 on 2022-09-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_article_time_alter_reply_time'),
        ('chatbot', '0004_counselor_user_name'),
    ]

    operations = [
    ]
